# Definitions import from WMBus_HCI_Spec_V1_6.pdf
IM871A_SERIAL_SOF = 0xA5
DEVMGMT_ID = 0x01
RADIOLINK_ID = 0x02
RADIOLINKTEST_ID = 0x03
HWTEST_ID = 0x04
TEMP_MEM = 0x00

DEVMGMT_MSG_PING_REQ = 0x01
DEVMGMT_MSG_PING_RSP = 0x02
DEVMGMT_MSG_SET_CONFIG_REQ = 0x03
DEVMGMT_MSG_SET_CONFIG_RSP = 0x04
DEVMGMT_MSG_GET_CONFIG_REQ = 0x05
DEVMGMT_MSG_GET_CONFIG_RSP = 0x06
DEVMGMT_MSG_RESET_REQ = 0x07
DEVMGMT_MSG_RESET_RSP = 0x08
DEVMGMT_MSG_FACTORY_RESET_REQ = 0x09
DEVMGMT_MSG_FACTORY_RESET_RSP = 0x0A
DEVMGMT_MSG_GET_OPMODE_REQ = 0x0B
DEVMGMT_MSG_GET_OPMODE_RSP = 0x0C
DEVMGMT_MSG_SET_OPMODE_REQ = 0x0D
DEVMGMT_MSG_SET_OPMODE_RSP = 0x0E
DEVMGMT_MSG_GET_DEVICEINFO_REQ = 0x0F
DEVMGMT_MSG_GET_DEVICEINFO_RSP = 0x10
DEVMGMT_MSG_GET_SYSSTATUS_REQ = 0x11
DEVMGMT_MSG_GET_SYSSTATUS_RSP = 0x12
DEVMGMT_MSG_GET_FWINFO_REQ = 0x13
DEVMGMT_MSG_GET_FWINFO_RSP = 0x14
DEVMGMT_MSG_GET_RTC_REQ = 0x19
DEVMGMT_MSG_GET_RTC_RSP = 0x1A
DEVMGMT_MSG_SET_RTC_REQ = 0x1B
DEVMGMT_MSG_SET_RTC_RSP = 0x1C
DEVMGMT_MSG_ENTER_LPM_REQ = 0x1D
DEVMGMT_MSG_ENTER_LPM_RSP = 0x1E
DEVMGMT_MSG_SET_AES_ENCKEY_REQ = 0x21
DEVMGMT_MSG_SET_AES_ENCKEY_RSP = 0x22
DEVMGMT_MSG_ENABLE_AES_ENCKEY_REQ = 0x23
DEVMGMT_MSG_ENABLE_AES_ENCKEY_RSP = 0x24
DEVMGMT_MSG_SET_AES_DECKEY_REQ = 0x25
DEVMGMT_MSG_SET_AES_DECKEY_RSP = 0x26
DEVMGMT_MSG_AES_DEC_ERROR_IND = 0x27

RADIOLINK_MSG_WMBUSMSG_REQ = 0x01
RADIOLINK_MSG_WMBUSMSG_RSP = 0x02
RADIOLINK_MSG_WMBUSMSG_IND = 0x03
RADIOLINK_MSG_DATA_REQ = 0x04
RADIOLINK_MSG_DATA_RSP = 0x05

RADIOLINKTEST_MSG_START_REQ = 0x01
RADIOLINKTEST_MSG_START_RSP = 0x02
RADIOLINKTEST_MSG_STOP_REQ = 0x03
RADIOLINKTEST_MSG_STOP_RSP = 0x04
RADIOLINKTEST_MSG_STATUS_IND = 0x07

HWTEST_MSG_RADIOTEST_REQ = 0x01
HWTEST_MSG_RADIOTEST_RSP = 0x02